[package]
name = "abc038"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc038-d = { alias = "d", problem = "https://atcoder.jp/contests/abc038/tasks/abc038_d" }

[[bin]]
name = "abc038-d"
path = "src/bin/d.rs"

[dependencies]
proconio = "0.4.3"

[dev-dependencies]
